export const Actiontypes = {
    SET_PRODUCTS: "SET_PRODUCTS",
    SELECTED_PRODUCT: "SELECTED_PRODUCT",
    REMOVE_SELECTED_PRODUCT : "REMOVE_SELECTED_PRODUCT",
    ADD_SELECTED_PRODUCT : "ADD_SELECTED_PRODUCT",
    REMOVE_CART_ITEMS : "REMOVE_CART_ITEMS"
}
